name: pixelblitz_app
description: A videogames zone
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  card_swiper: ^2.0.4
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  go_router: ^8.0.5

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/logos/
    - .env

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
        - asset: assets/fonts/Satoshi-Bold.ttf
        - asset: assets/fonts/Satoshi-Light.ttf
        - asset: assets/fonts/Satoshi-Medium.ttf
        - asset: assets/fonts/Satoshi-Regular.ttf
