name: pixelblitz_app
description: A videogames zone
publish_to: 'none'
version: 1.1.0+3

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  card_swiper: ^3.0.1
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  go_router: ^9.0.3
  intl: ^0.18.1
  lottie: ^2.4.0
  package_info_plus: ^4.0.2
  shimmer: ^3.0.0
  url_launcher: ^6.1.12

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#121214"
  image: "assets/images/logos/logo-splash-screen.png"
  android_12:
    icon_background_color: "#121214"
    image: "assets/images/logos/logo-splash-screen.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/logos/
    - assets/images/animations/
    - .env

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
        - asset: assets/fonts/Satoshi-Bold.ttf
        - asset: assets/fonts/Satoshi-Light.ttf
        - asset: assets/fonts/Satoshi-Medium.ttf
        - asset: assets/fonts/Satoshi-Regular.ttf
